Use newer flake8 to run on ubuntu-focal Zuul machines
flake8 3.5.0  fails on ubuntu-focal zuul machines running python3.8
with the following error:
AttributeError: 'FlakesChecker' object has no attribute 'CONSTANT'

The update removes the version constraint to use newer flake8.  This
also ignores new warnings/errors, which should be addressed in a
future update to remove the ignores.

Change-Id: I16dc579f7ee803881c42ff6048ddd2f6bb0c553b
Partial-Bug: 1895054
Signed-off-by: Don Penney <don.penney@windriver.com>
(cherry picked from commit fcae730d65fe145e76a3d384360327a6b8f61c44)