rvmc: remove un-used build data
The  error below reported in the build logs because rvmc is not
setup to be built as an RPM package.

ERROR: build_dir (425): Neither srpm_path nor .spec file not found
in '/localdisk/designer/swold/stx/cgcs-root/stx/metal/tools/rvmc/centos'

Closes-Bug: 1859893

Change-Id: I9b2788bb227afbdf49e2faa5f05628331719233e
Signed-off-by: Saul Wold <sgw@linux.intel.com>